version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: sail-8.3/app
    environment:
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/recruit-app'
      - 'vendor_volume:/recruit-app/vendor'
    networks:
      - sail

  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recruit_app
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

  nginx:
    image: nginx:alpine
    volumes:
      - '.:/recruit-app'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
    networks:
      - sail
    depends_on:
      - web

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  vendor_volume:
    driver: local
